FROM python:3.14-slim

WORKDIR /app

COPY project1/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY project1 ./project1

EXPOSE 8000

CMD ["uvicorn", "project1.main:app", "--host", "0.0.0.0", "--port", "8000"]