FROM python:3.14-slim

WORKDIR /app/project1

COPY project1/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY project1 .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]